{% set name = "flupy" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flupy-{{ version }}.tar.gz
  sha256: c28ff659b55800a26a64dd0ac1cc616355900718b87978c2db06f5e5cfb58535

build:
  entry_points:
    - flu = flupy.cli.cli:main
    - flu_precommit = flupy.cli.cli:precommit
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=4

test:
  imports:
    - flupy
  commands:
    - pip check
    - flu --help  # [not win]
    - flu_precommit --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/olirice/flupy
  summary: Fluent data processing in Python - a chainable stream processing library for expressive data manipulation using method chaining
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - abraha2d
